disp("kNN test for spectral centroid: ");
test_feature(C4, C5, C6, C1, C2, C3);
disp("kNN test for spectral spread: ");
test_feature(S4, S5, S6, S1, S2, S3);
disp("kNN test for spectral rolloff: ");
test_feature(R4, R5, R6, R1, R2, R3);
disp("kNN test for mfccs: ");
test_feature(ceps4, ceps5, ceps6, ceps1, ceps2, ceps3);
disp("kNN test for zcr: ");
test_feature(Z4, Z5, Z6, Z1, Z2, Z3);
disp("kNN test for energy: ");
test_feature(E4, E5, E6, E1, E2, E3);