disp("kNN test for spectral centroid: ");
test_feature(C4, C1, C6, C3, C2, C5);
disp("kNN test for spectral spread: ");
test_feature(S4, S1, S6, S3, S2, S5);
disp("kNN test for spectral rolloff: ");
test_feature(R4, R1, R6, R3, R2, R5);
disp("kNN test for mfccs: ");
test_feature(ceps4, ceps1, ceps6, ceps3, ceps2, ceps5);
disp("kNN test for zcr: ");
test_feature(Z4, Z1, Z6, Z3, Z2, Z5);
disp("kNN test for energy: ");
test_feature(E4, E1, E6, E3, E2, E5);