disp("kNN test for spectral centroid: ");
test_feature(C1, C6, C3, C4, C5, C2);
disp("kNN test for spectral spread: ");
test_feature(S1, S6, S3, S4, S5, S2);
disp("kNN test for spectral rolloff: ");
test_feature(R1, R6, R3, R4, R5, R2);
disp("kNN test for mfccs: ");
test_feature(ceps1, ceps6, ceps3, ceps4, ceps5, ceps2);
disp("kNN test for zcr: ");
test_feature(Z1, Z6, Z3, Z4, Z5, Z2);
disp("kNN test for energy: ");
test_feature(E1, E6, E3, E4, E5, E2);